# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63rawl.proto\x12\x04grpc\"\x18\n\x06Worker\x12\x0e\n\x06number\x18\x01 \x01(\x05\"8\n\x04Task\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\",\n\x08Response\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x05\"\x16\n\x03\x41\x63k\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"[\n\x07\x43omment\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x05\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x11\n\tworker_id\x18\x04 \x01(\x05\x12\r\n\x05isBad\x18\x05 \x01(\x05\x32\x89\x02\n\x05\x43rawl\x12,\n\x0c\x43reateWorker\x12\x0c.grpc.Worker\x1a\x0e.grpc.Response\x12(\n\nTaskStream\x12\x0c.grpc.Worker\x1a\n.grpc.Task0\x01\x12&\n\x08SentTask\x12\n.grpc.Task\x1a\x0e.grpc.Response\x12(\n\rSendHeartbeat\x12\x0c.grpc.Worker\x1a\t.grpc.Ack\x12%\n\x07LogTask\x12\x0c.grpc.Worker\x1a\n.grpc.Task0\x01\x12/\n\x0eReceiveComment\x12\r.grpc.Comment\x1a\x0e.grpc.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKER._serialized_start=21
  _WORKER._serialized_end=45
  _TASK._serialized_start=47
  _TASK._serialized_end=103
  _RESPONSE._serialized_start=105
  _RESPONSE._serialized_end=149
  _ACK._serialized_start=151
  _ACK._serialized_end=173
  _COMMENT._serialized_start=175
  _COMMENT._serialized_end=266
  _CRAWL._serialized_start=269
  _CRAWL._serialized_end=534
# @@protoc_insertion_point(module_scope)
